version: '3.8'

services:
  cronicle:
    build:
      context: ./cronicle
      dockerfile: Dockerfile
    container_name: cronicle
    restart: unless-stopped
    ports:
      - "${PORT:-3012}:3012"
    volumes:
      - cronicle_data:/opt/cronicle/data
      - cronicle_data:/opt/cronicle/logs
    environment:
      CRONICLE_debug_level: 9
      CRONICLE_base_url: ${RAILWAY_STATIC_URL:-http://localhost:3012}
      PORT: ${PORT:-3012}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://cronicle:3012/api/app/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  cronicle_data:
    driver: local