[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/api/app/ping"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
CRONICLE_base_url = "https://${{RAILWAY_STATIC_URL}}"
CRONICLE_debug_level = "9"
PORT = "3012"

[[volumes]]
name = "cronicle_data"
mountPath = "/opt/cronicle/data"

[[volumes]]
name = "cronicle_logs"
mountPath = "/opt/cronicle/logs"